# Packet types
HANDSHAKE = 0
HANDSHAKE_ACCEPT = 1
LOOKUP = 2
FOUND = 3
REQUEST_STREAM = 4
READY_TO_STREAM = 5
REQUEST_PART = 6
CONTENT = 7

# Parser states
RECEIVING_HEADER = 8
RECEIVING_CONTENT = 9
PACKET_RECEIVED = 10
