# Packet types
HANDSHAKE = 0
HANDSHAKE_ACCEPT = 1
LOOKUP = 2
FOUND = 3
REQUEST_SREAM = 4
READY_TO_STREAM = 5
REQUEST_PART = 6
CONTENT = 7

# Parser states
RECEIVING_HEADERS = 8
RECEIVING_EX_HEADERS = 9
RECEIVING_CONTENT = 10 
PACKET_RECEIVED = 11
